version: '3.3'

services:
  portfolio-lorys-nginx:
    image: nginx:1.25.2-perl
    container_name: portfolio-lorys-nginx
    restart: always
    networks:
      - traefik_network
    volumes:
      - ./public:/usr/share/nginx/html
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.portfolio-lorys.rule=Host(`lorys-mallet.com`)'
      - 'traefik.http.routers.portfolio-lorys.entrypoints=web, websecure'
      - 'traefik.http.routers.portfolio-lorys.tls=true'
      - 'traefik.http.routers.portfolio-lorys.tls.certresolver=letsencrypt'
      - 'traefik.http.services.portfolio-lorys.loadbalancer.server.port=80'

networks:
  traefik_network:
    external: true
